import 'package:yaumi/models/yaumi.dart';

class YaumiTemp {
  List<Yaumi> data = [
    Yaumi(
        date: DateTime(2024, 3, 23),
        shubuh: true,
        dhuhur: true,
        ashar: true,
        maghrib: true,
        isya: true,
        tahajud: 7,
        dhuha: 4,
        qshubuh: true,
        qdhuhur: true,
        bdhuhur: true,
        bmaghrib: true,
        bisya: true,
        tilawah: 10,
        poin: 70,
        shaumSunnah: ShaumSunnah.shaumRamadhan,
        dzikirPagi: true,
        dzikirPetang: true,
        taklim: Taklim.taklimOnline,
        istighfar: true,
        shalawat: true),
    Yaumi(
        date: DateTime(2024, 3, 24),
        shubuh: false,
        dhuhur: true,
        ashar: true,
        maghrib: true,
        isya: true,
        tahajud: 7,
        dhuha: 4,
        qshubuh: true,
        qdhuhur: true,
        bdhuhur: true,
        bmaghrib: true,
        bisya: true,
        tilawah: 10,
        poin: 70,
        shaumSunnah: ShaumSunnah.shaumRamadhan,
        dzikirPagi: true,
        dzikirPetang: true,
        taklim: Taklim.taklimOnline,
        istighfar: true,
        shalawat: true),
  ];
}
